services:
  crafty:
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    container_name: crafty-controller
    restart: unless-stopped
    ports:
      - "8443:8443"
      - "25500-25600:25500-25600"
    volumes:
      - ./docker/backups:/crafty/backups
      - ./docker/logs:/crafty/logs
      - ./docker/servers:/crafty/servers
      - ./docker/config:/crafty/app/config
      - ./docker/import:/crafty/import
    networks:
      - proxy

networks:
  proxy:
    external: true
