services:
  adguard:
    image: adguard/adguardhome:v0.107.78
    container_name: adguard
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./data/work:/opt/adguardhome/work
      - ./data/conf:/opt/adguardhome/conf
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.adguard.rule=Host(`adguard.rubenlav.dev`)
      - traefik.http.routers.adguard.entrypoints=websecure
      - traefik.http.services.adguard.loadbalancer.server.port=80

networks:
  proxy:
    external: true
