services:
  dozzle:
    image: amir20/dozzle:v8
    container_name: dozzle
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.dozzle.rule=Host(`dozzle.rubenlav.dev`)
      - traefik.http.routers.dozzle.entrypoints=websecure
      - traefik.http.services.dozzle.loadbalancer.server.port=8080

networks:
  proxy:
    external: true
